services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ../web:/var/www
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    build: ./php-fpm
    volumes:
      - ../web:/var/www
      - ./php-fpm/php8.3.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
